### ISSUE TITLE
Unable to harvest/exchange unless minter is set to the LATokenMinter contract

### ISSUE THREAD

**Issue by IsaacPayne** [BlockchainLabsNZ/LAToken-Contracts-Audit#34]
The minter contract address needs to be set as the [minter](https://github.com/ElKornacio/contracts-early/blob/master/contracts/base-token/LATToken.sol#L93) to [harvest](https://github.com/ElKornacio/contracts-early/blob/master/contracts/LATokenMinter.sol#L105) or [exchange](https://github.com/ElKornacio/contracts-early/blob/master/contracts/ExchangeContract.sol#L41) but needs to be set to a standard ethereum address to [burn](https://github.com/ElKornacio/contracts-early/blob/master/contracts/base-token/LATToken.sol#L70)

**Comment by matt-lough** [comment]
When you call the `harvest` function it calls `issueTokens` in the token contract [here](https://github.com/BlockchainLabsNZ/LAToken-Contracts-Audit/blob/master/contracts/LATokenMinter.sol#L54)

`issueTokens` has an `onlyMinter` modifier on it, since this function is being called from `harvest` the `msg.sender` when it reaches `issueTokens` is the contract address of the minter. [here](https://github.com/BlockchainLabsNZ/LAToken-Contracts-Audit/blob/master/contracts/base-token/LATToken.sol#L55)

To get around this you can set the minter contract address as the minter for your token, but this means that the `exchanger` can not exchange until you change the minter to the exchange contracts address.

If this isn't clear then please feel free to shoot us a message.

**Comment by salis** [comment]
@ElKornacio `minter` can't be responsible for burning. Would `founder` be the right address for calling `burn`?

**Comment by matt-lough** [comment]
Fixed https://github.com/BlockchainLabsNZ/LAToken-Contracts-Audit/commit/7ae186fe3ccd92898fbe3d3eb8007e6e6c65d95a
